# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
# This is a YAML-formatted file
# Declare variables to be passed into your templates.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: "{{ .Values.namespace }}"
  labels:
    {{- ( include "labels" . ) | indent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.applicationPort }}
      targetPort: {{ .Values.applicationPort }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}